import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CIDEY",
  description: "Generated by create next app",
  icons: {
    icon: "blob:https://tools.kommodo.ai/314a93fe-995d-4244-bc9e-4e2beb74bde5",
  },
  other: {
    monetag: "96c630df9f532399eb8c5b7b2c2d805d",
    "profiton-domain-verification": "85362818e8f6a71c6087d03c58415e8550c3b10bda84bc32d065e27a094b348e",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}